name: weather_app
description: Weather app

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.3.1
  injectable: ^2.1.0
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  form_builder_validators: ^8.4.0
  flutter_form_builder: ^7.7.0
  shared_preferences: ^2.0.17
  syncfusion_flutter_charts: ^20.4.48
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
